### PR TITLE
Fix the tests so that they run

### PR DESCRIPTION
**Pull request by jjm**
Remove the execute bit on tests, so the `nose` will detect them and run the tests (Fixes: #5).

### CODE REVIEW

**Comment by Kami** [comment]
Good catch - thanks again.

On a related note - we should add a check to the `make compile` or similar target which checks that no files in tests/ starting with `test_` have an executable bit.

Bonus point would also be documenting this in testing guide in st2docs :)

**Comment by jjm** [comment]
Looks like this needs the fix your currently working on for aliases too.

How about I add a `+x` check for `test_*` files to a general linting script in `st2sdk` that checks *all* files for errors and then reports instead of stopping at the first one?

That's an annoyance I found when sorting CI for our internal pack. Marking the pack testing story for our internal pack better is is something I'm thinking about.

**Comment by Kami** [comment]
@jjm Yeah, I'm fine with adding that check script / tool to `st2sdk` and then calling it inside the Circle CI task which runs for all the packs :)

**Comment by jjm** [comment]
I'll just close this, it was fixed else where.

**Pull request closed without merging**
