### PR TITLE
New actions to create repository + bug fix + segure improvement on github token

### PR DESCRIPTION
**Pull request by MarlonHeiber**
* Add new ``github.create_organization_repository`` action which allows user to create an organization repository.
* Add new ``github.create_repository_authenticated_user`` action which allows user to create an user repository.
* Add new ``github.create_repository_from_template`` action which allows user to create a repository from template.
* Bug fix on ``github.store_oauth_token`` to api save the token correctly so that it can be read later.
* Segure improvement on ``github.store_oauth_token`` to encrypt de github token in web interface.

### CODE REVIEW

**Review by nzlosh — APPROVED** [review]
LGTM

**Comment by MarlonHeiber** [comment]
Hello
Is something missing to merge this PR?

**Comment by MarlonHeiber** [comment]
@nzlosh @armab

**Comment by nzlosh** [comment]
Thank you for the contribution and sorry about the delay getting this merged.

**Comment by nzlosh** [comment]
@MarlonHeiber I had to revert this PR because it failed tests after I fixed the linting issues.  https://github.com/StackStorm-Exchange/stackstorm-github/runs/7317793014?check_suite_focus=true

**Pull request merged**
