### PR TITLE
Bugfix/action/get contents with decode parameter

### LINKED ISSUE #41: The "github.get_contents" action will fail when decode parameter is set
When I run following action, it succeed in running this action.
`$ st2 run github.get_contents user=StackStorm repo=st2 path=/LICENSE`

But following action, which adds `decode` parameter, will fail as below.
`$ st2 run github.get_contents user=StackStorm repo=st2 path=/LICENSE decode=True`

Here is a result of running this action with `decode` parameter.
```
ubuntu@localhost:~$ st2 run github.get_contents user=StackStorm repo=st2 path=/LICENSE decode=True
.
id: 60efae5db289e9717c9b1103
action.ref: github.get_contents
context.user: st2admin
parameters: 
  decode: true
  path: /LICENSE
  repo: st2
  user: StackStorm
status: failed
start_timestamp: Thu, 15 Jul 2021 03:41:17 UTC
end_timestamp: Thu, 15 Jul 2021 03:41:18 UTC
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 395, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 214, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/github/actions/get_contents.py", line 15, in run
    result = contents_to_dict(contents=contents, decode=decode)
  File "/opt/stackstorm/packs/github/actions/lib/formatters.py", line 212, in contents_to_dict
    content = decode_base64(content)
  File "/opt/stackstorm/packs/github/actions/lib/formatters.py", line 240, in decode_base64
    data += b'=' * (4 - missing_padding)
TypeError: can only concatenate str (not "bytes") to str
"
  stdout: ''
```

And here is my ST2 environment that I ran those actions.
```
ubuntu@localhost:~$ st2 --version
st2 3.5.0, on Python 3.8.5
ubuntu@localhost:~$ st2 pack get github
+-------------+--------------------------+
| Property    | Value                    |
+-------------+--------------------------+
| name        | github                   |
| version     | 2.0.1                    |
| author      | StackStorm, Inc.         |
| email       | info@stackstorm.com      |
| keywords    | [                        |
|             |     "github",            |
|             |     "github enterprise", |
|             |     "git",               |
|             |     "scm",               |
|             |     "serverless"         |
|             | ]                        |
| description | GitHub integration       |
+-------------+--------------------------+
ubuntu@localhost:~$ 
```

### PR DESCRIPTION
**Pull request by userlocalhost**
Close: #41 

This commit changed decoding processing of getting content to use ContentFile.decoded_content method instead of self-implemented one.
Because the PyGithub, which this pack depends on, have already implemented decoding processing for content of ContentFile as below.
https://github.com/PyGithub/PyGithub/blob/v1.45/github/ContentFile.py#L58-L61

### CODE REVIEW

**Comment by blag** [comment]
This looks good. Please rebase this on the current `master` (sorry I updated after you opened your PR).

It would be nice if we fixed the `decode_base64` as well, or removed it and every usage of it.

**Comment by userlocalhost** [comment]
Thank you very much for your review. I got it.

**Review by arm4b — APPROVED** [review]

**Comment by arm4b** [comment]
@userlocalhost is the change here still actual, can I merge it?
Sorry, my bad. I thought you had write access in this repo to merge it by yourself.

**Comment by RishabhDev42** [comment]
@userlocalhost @armab Faced the same issue. 
image
After pulling the fix, it works however
image
I wanted to follow up with ETA on the merge of this fix?

**Pull request merged**
